spring:
    profiles:
        active: test
        include: google, jwt, log
    h2:
        console:
            enabled: true

---

spring:
    profiles:
        active: dev
        include: google, postgresql, jwt

---

spring:
    profiles:
        active: real
        include: google, postgresql, jwt