spring:
    profiles:
        active: test
        include: google, jwt
    h2:
        console:
            enabled: true
    # 프로퍼티 파일명을 application-XXX.properties 이런 식으로 지으면, 위에 처럼 spring.profiles.include=XXX 로 로딩할 수 있습니다.

---

spring:
    profiles:
        active: dev
        include: google, postgresql, jwt

---

spring:
    profiles:
        active: real
        include: google, postgresql, jwt