# Postgresql & JPA
spring:
  datasource:
    url: jdbc:postgresql://yh01-20studio.cr6bofelpl5h.ap-northeast-2.rds.amazonaws.com:5432/springboot-web?stringtype=unspecified
    username: yh20studio
    password: youngho9169!
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

