spring:
  profiles:
    active: dev
---
spring:
  profiles:
    group:
      "test": "jwt,postgresqltest"
      "dev": "jwt,postgresql"
---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: dev
