spring:
    profiles:
        group:
            "test": "google,jwt,postgresqltest"
            "dev": "google,jwt,postgresql"
---
spring:
    config:
        activate:
            on-profile: test
---
spring:
    config:
        activate:
            on-profile: dev
